-- ========================================
-- 샘플 테이블 생성 스크립트
-- Oracle Database용 (12c 이상 권장)
-- ========================================

-- 주의: 스키마는 현재 접속 사용자로 생성됩니다. 필요 시 다른 스키마로 변경하세요.

-- 기존 객체 삭제 (존재 시)
BEGIN EXECUTE IMMEDIATE 'DROP VIEW vw_OrderSummary'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE OrderDetails CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Orders CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Products CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Employees CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Customers CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- ========================================
-- 1. Customers 테이블
-- ========================================
CREATE TABLE Customers (
  CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  CustomerCode VARCHAR2(20) NOT NULL,
  CustomerName VARCHAR2(100) NOT NULL,
  ContactName VARCHAR2(50),
  Email VARCHAR2(100),
  Phone VARCHAR2(20),
  Address VARCHAR2(200),
  City VARCHAR2(50),
  Region VARCHAR2(50),
  PostalCode VARCHAR2(10),
  Country VARCHAR2(50),
  CustomerType VARCHAR2(20) DEFAULT 'Regular',
  CreditLimit NUMBER(15,2) DEFAULT 0,
  IsActive NUMBER(1) DEFAULT 1,
  CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  LastUpdated TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_Customers PRIMARY KEY (CustomerID),
  CONSTRAINT UK_Customers_Code UNIQUE (CustomerCode)
);

CREATE INDEX IX_Customers_Name ON Customers (CustomerName);
CREATE INDEX IX_Customers_City ON Customers (City);
CREATE INDEX IX_Customers_Region ON Customers (Region);
CREATE INDEX IX_Customers_Type ON Customers (CustomerType);

-- LastUpdated 자동 업데이트 트리거
CREATE OR REPLACE TRIGGER trg_customers_modtime
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
  :NEW.LastUpdated := SYSTIMESTAMP;
END;
/

-- ========================================
-- 2. Orders 테이블
-- ========================================
CREATE TABLE Orders (
  OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  OrderNumber VARCHAR2(30) NOT NULL,
  CustomerID NUMBER NOT NULL,
  OrderDate TIMESTAMP NOT NULL,
  RequiredDate TIMESTAMP,
  ShippedDate TIMESTAMP,
  OrderStatus VARCHAR2(20) DEFAULT 'Pending',
  SubTotal NUMBER(15,2) DEFAULT 0,
  TaxAmount NUMBER(15,2) DEFAULT 0,
  TotalAmount NUMBER(15,2) DEFAULT 0,
  PaymentMethod VARCHAR2(30),
  PaymentStatus VARCHAR2(20) DEFAULT 'Unpaid',
  EmployeeID NUMBER,
  Notes VARCHAR2(500),
  CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  LastUpdated TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_Orders PRIMARY KEY (OrderID),
  CONSTRAINT UK_Orders_Number UNIQUE (OrderNumber),
  CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE INDEX IX_Orders_CustomerID ON Orders (CustomerID);
CREATE INDEX IX_Orders_OrderDate ON Orders (OrderDate);
CREATE INDEX IX_Orders_Status ON Orders (OrderStatus);
CREATE INDEX IX_Orders_PaymentStatus ON Orders (PaymentStatus);
CREATE INDEX IX_Orders_ShippedDate ON Orders (ShippedDate);

CREATE OR REPLACE TRIGGER trg_orders_modtime
BEFORE UPDATE ON Orders
FOR EACH ROW
BEGIN
  :NEW.LastUpdated := SYSTIMESTAMP;
END;
/

-- ========================================
-- 3. Products 테이블
-- ========================================
CREATE TABLE Products (
  ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ProductCode VARCHAR2(20) NOT NULL,
  ProductName VARCHAR2(100) NOT NULL,
  Category VARCHAR2(50),
  UnitPrice NUMBER(15,2) DEFAULT 0,
  UnitsInStock NUMBER DEFAULT 0,
  UnitsOnOrder NUMBER DEFAULT 0,
  ReorderLevel NUMBER DEFAULT 0,
  Discontinued NUMBER(1) DEFAULT 0,
  Description CLOB,
  CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  LastUpdated TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_Products PRIMARY KEY (ProductID),
  CONSTRAINT UK_Products_Code UNIQUE (ProductCode)
);

CREATE INDEX IX_Products_Name ON Products (ProductName);
CREATE INDEX IX_Products_Category ON Products (Category);
CREATE INDEX IX_Products_Price ON Products (UnitPrice);

CREATE OR REPLACE TRIGGER trg_products_modtime
BEFORE UPDATE ON Products
FOR EACH ROW
BEGIN
  :NEW.LastUpdated := SYSTIMESTAMP;
END;
/

-- ========================================
-- 4. OrderDetails 테이블
-- ========================================
CREATE TABLE OrderDetails (
  OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  OrderID NUMBER NOT NULL,
  ProductID NUMBER NOT NULL,
  UnitPrice NUMBER(15,2) NOT NULL,
  Quantity NUMBER NOT NULL,
  Discount NUMBER(5,2) DEFAULT 0,
  LineTotal NUMBER(15,2) GENERATED ALWAYS AS (UnitPrice * Quantity * (1 - Discount/100)) VIRTUAL,
  CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_OrderDetails PRIMARY KEY (OrderDetailID),
  CONSTRAINT FK_OrderDetails_Orders FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
  CONSTRAINT FK_OrderDetails_Products FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE INDEX IX_OrderDetails_OrderID ON OrderDetails (OrderID);
CREATE INDEX IX_OrderDetails_ProductID ON OrderDetails (ProductID);

-- ========================================
-- 5. Employees 테이블
-- ========================================
CREATE TABLE Employees (
  EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY,
  EmployeeCode VARCHAR2(20) NOT NULL,
  FirstName VARCHAR2(50) NOT NULL,
  LastName VARCHAR2(50) NOT NULL,
  Title VARCHAR2(50),
  BirthDate DATE,
  HireDate DATE,
  Email VARCHAR2(100),
  Phone VARCHAR2(20),
  Department VARCHAR2(50),
  Salary NUMBER(15,2),
  ReportsTo NUMBER,
  IsActive NUMBER(1) DEFAULT 1,
  CreatedDate TIMESTAMP DEFAULT SYSTIMESTAMP,
  LastUpdated TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_Employees PRIMARY KEY (EmployeeID),
  CONSTRAINT UK_Employees_Code UNIQUE (EmployeeCode),
  CONSTRAINT FK_Employees_ReportsTo FOREIGN KEY (ReportsTo) REFERENCES Employees(EmployeeID)
);

CREATE INDEX IX_Employees_Name ON Employees (LastName, FirstName);
CREATE INDEX IX_Employees_Department ON Employees (Department);
CREATE INDEX IX_Employees_ReportsTo ON Employees (ReportsTo);

CREATE OR REPLACE TRIGGER trg_employees_modtime
BEFORE UPDATE ON Employees
FOR EACH ROW
BEGIN
  :NEW.LastUpdated := SYSTIMESTAMP;
END;
/

-- ========================================
-- 6. 주문 요약 뷰
-- ========================================
CREATE OR REPLACE VIEW vw_OrderSummary AS
SELECT 
  o.OrderID,
  o.OrderNumber,
  o.OrderDate,
  c.CustomerCode,
  c.CustomerName,
  c.City AS CustomerCity,
  c.Region AS CustomerRegion,
  o.OrderStatus,
  o.PaymentStatus,
  o.TotalAmount,
  (SELECT COUNT(*) FROM OrderDetails od WHERE od.OrderID = o.OrderID) AS ItemCount,
  (SELECT NVL(SUM(od.Quantity),0) FROM OrderDetails od WHERE od.OrderID = o.OrderID) AS TotalQuantity,
  o.CreatedDate
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID;

-- 완료 메시지
PROMPT 'Oracle용 샘플 테이블 생성 완료'
